services:
  - type: db
    name: tts-db
    plan: free
    runtime: postgres
    ipAllowList: [] # Only allow internal connections

  - type: web
    name: tts-server
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tts-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0
